package com.example.demo.bean;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.u_id
     *
     * @mbggenerated Fri Nov 02 18:17:40 CST 2018
     */
    private Long uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.u_name
     *
     * @mbggenerated Fri Nov 02 18:17:40 CST 2018
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.u_age
     *
     * @mbggenerated Fri Nov 02 18:17:40 CST 2018
     */
    private Integer uAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.u_desc
     *
     * @mbggenerated Fri Nov 02 18:17:40 CST 2018
     */
    private String uDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.u_id
     *
     * @return the value of t_user.u_id
     *
     * @mbggenerated Fri Nov 02 18:17:40 CST 2018
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.u_id
     *
     * @param uId the value for t_user.u_id
     *
     * @mbggenerated Fri Nov 02 18:17:40 CST 2018
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.u_name
     *
     * @return the value of t_user.u_name
     *
     * @mbggenerated Fri Nov 02 18:17:40 CST 2018
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.u_name
     *
     * @param uName the value for t_user.u_name
     *
     * @mbggenerated Fri Nov 02 18:17:40 CST 2018
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.u_age
     *
     * @return the value of t_user.u_age
     *
     * @mbggenerated Fri Nov 02 18:17:40 CST 2018
     */
    public Integer getuAge() {
        return uAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.u_age
     *
     * @param uAge the value for t_user.u_age
     *
     * @mbggenerated Fri Nov 02 18:17:40 CST 2018
     */
    public void setuAge(Integer uAge) {
        this.uAge = uAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.u_desc
     *
     * @return the value of t_user.u_desc
     *
     * @mbggenerated Fri Nov 02 18:17:40 CST 2018
     */
    public String getuDesc() {
        return uDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.u_desc
     *
     * @param uDesc the value for t_user.u_desc
     *
     * @mbggenerated Fri Nov 02 18:17:40 CST 2018
     */
    public void setuDesc(String uDesc) {
        this.uDesc = uDesc == null ? null : uDesc.trim();
    }
}